name: release workflow
on:
  workflow_dispatch:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: sudo apt-get update
    - run: sudo apt-get install libipc-run-perl libfile-slurp-perl qemu-user qemu-user-static binfmt-support gettext xz-utils qemu-system-aarch64 sharutils
    - run: git clone https://github.com/pipcet/dg -b main
    - name: Set env variables
      uses: ./dg/github/env/
    - run: echo 1 | sudo tee /proc/sys/vm/overcommit_memory
    - run: make PACKAGE=user-setup -f dg/dg.mk dg/build/packages.tar
    - run: make PACKAGE=user-setup -f dg/dg.mk {deversion-udeb}
    - run: make PACKAGE=user-setup -f dg/dg.mk {release-udeb}
    - run: make PACKAGE=user-setup -f dg/dg.mk {release}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
